### PR TITLE
Updated to Bootstrap+Haml and removed deprecated methods

### PR DESCRIPTION
**Pull request by thekeith**
Fixed issues #4 #5 and #6 

The main gist is moving to bootstrap + haml to make general use a lot easier on the eye and sate my own UX tastes. I also removed some deprecated controller methods, as well as fixing a few bugs.

### CODE REVIEW

**Comment by thekeith** [comment]
Would be good if I finalized the whole PR before making it.

**Comment by carlsednaoui** [comment]
Damn, what are your plans with this little scraper — feels like it's becoming a full-on application :smile: :hamburger:

**Comment by thekeith** [comment]
I've got thoughts around that. It is a tool I'd like to automate so that I can have it crawling thousands of terms.

**Comment by thekeith** [comment]
The other thought is to rename and add functionality that would make it easier to use for other SEO related tasks too. Like indexing your inbound links, watching new links come in, integrating with MajesticSEO, etc.

All loose ideas for now. I'll think about it more, but at this point it is 50% to what I'd like to automatic daily usage.

**Comment by carlsednaoui** [comment]
Sounds great — would love to hear more when we chat!

**Pull request closed without merging**
